/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

#include "UcacheBenchClient.h"

#include <fmt/format.h>
#include <folly/Format.h>
#include <folly/Random.h>
#include <folly/dynamic.h>
#include <folly/json.h>

#include <folly/fibers/Baton.h>
#include <folly/io/IOBuf.h>
#include <folly/portability/GFlags.h>
#include <algorithm>
#include <fstream>
#include <thread>

using namespace facebook::ucachebench;

DEFINE_string(server_host, "localhost", "Server hostname");
DEFINE_uint32(server_port, 11211, "Server port");
DEFINE_uint32(duration_seconds, 60, "Test duration in seconds");
DEFINE_uint32(warmup_seconds, 10, "Warmup duration in seconds");
DEFINE_uint32(key_count, 100000, "Number of unique keys");
DEFINE_uint32(value_size_min, 64, "Minimum value size in bytes");
DEFINE_uint32(value_size_max, 1024, "Maximum value size in bytes");
DEFINE_double(get_ratio, 0.9, "Ratio of GET operations (vs SET operations)");
DEFINE_uint32(qps_target, 0, "Target QPS (0 = unlimited)");
DEFINE_uint32(
    connection_timeout_ms,
    1000,
    "Connection timeout in milliseconds");
DEFINE_uint32(send_timeout_ms, 1000, "Send timeout in milliseconds");
DEFINE_string(
    security_mech,
    "plain",
    "Security mechanism for mcrouter (plain, tls_to_plain, fizz, etc.)");
DEFINE_uint32(
    num_proxies,
    0,
    "Number of mcrouter proxy threads (0 = auto-detect using hardware_concurrency)");
DEFINE_uint32(
    max_inflight,
    1,
    "Maximum number of concurrent in-flight requests (higher = better throughput, requires more memory)");
DEFINE_uint32(
    num_threads,
    0,
    "Number of client worker threads for request generation (0 = auto-detect, recommended: 4-16)");
DEFINE_uint32(
    additional_fanout,
    0,
    "Number of additional connections per server for fanout (0 = disabled, must be <= 32768 - num_proxies)");
DEFINE_bool(
    enable_random_source_ip,
    false,
    "Enable random source IP addresses for connection fanout (works with BucketHashSelector)");
DEFINE_bool(verbose, false, "Enable verbose logging");
DEFINE_bool(
    use_distribution,
    false,
    "Use production traffic distribution for key/value sizes");
DEFINE_string(
    distribution_config,
    "",
    "Path to JSON file with traffic distribution config (generated by parse_traffic_distribution.py)");

namespace facebook {
namespace ucachebench {

UcacheBenchClient::UcacheBenchClient() {
  // Load traffic distribution if configured
  if (FLAGS_use_distribution) {
    if (FLAGS_distribution_config.empty()) {
      throw std::runtime_error(
          "Must specify --distribution_config when --use_distribution=true");
    }
    loadTrafficDistribution(FLAGS_distribution_config);
    distribution_.enabled = true;

    if (FLAGS_verbose) {
      printf(
          "Loaded production traffic distribution from: %s\n",
          FLAGS_distribution_config.c_str());
      printf("  GET ratio: %.4f\n", distribution_.getRatio);
      printf("  GET key size (avg): %.2f bytes\n", distribution_.getKeySizeAvg);
      printf(
          "  SET value size (avg): %.2f bytes\n",
          distribution_.setValueSizeAvg);
    }
  }

  // Create mcrouter options for Thrift transport
  facebook::memcache::McrouterOptions options;

  // Configure for Thrift transport to ucache server
  // Build pool config with optional additional_fanout for high connection count
  std::string poolConfig;
  if (FLAGS_additional_fanout > 0) {
    poolConfig = folly::sformat(
        R"json({{
    "pools": {{
      "ucache_pool": {{
        "servers": [ "{}:{}" ],
        "protocol": "thrift",
        "security_mech": "{}",
        "connect_timeout_ms": {},
        "server_timeout_ms": {},
        "additional_fanout": {}
      }}
    }},
    "route": {{
      "type": "PoolRoute",
      "pool": "ucache_pool"
    }}
  }})json",
        FLAGS_server_host,
        FLAGS_server_port,
        FLAGS_security_mech,
        FLAGS_connection_timeout_ms,
        FLAGS_send_timeout_ms,
        FLAGS_additional_fanout);
  } else {
    poolConfig = folly::sformat(
        R"json({{
    "pools": {{
      "ucache_pool": {{
        "servers": [ "{}:{}" ],
        "protocol": "thrift",
        "security_mech": "{}",
        "connect_timeout_ms": {},
        "server_timeout_ms": {}
      }}
    }},
    "route": {{
      "type": "PoolRoute",
      "pool": "ucache_pool"
    }}
  }})json",
        FLAGS_server_host,
        FLAGS_server_port,
        FLAGS_security_mech,
        FLAGS_connection_timeout_ms,
        FLAGS_send_timeout_ms);
  }
  options.config_str = poolConfig;

  // Set num_proxies to use multiple threads for sending traffic
  // This allows mcrouter to distribute work across multiple proxy threads
  if (FLAGS_num_proxies == 0) {
    // Auto-detect using hardware concurrency
    options.num_proxies = std::thread::hardware_concurrency();
  } else {
    options.num_proxies = FLAGS_num_proxies;
  }

  // Create CarbonRouterInstance with UcacheBench RouterInfo
  auto routerPtr = facebook::memcache::mcrouter::CarbonRouterInstance<
      UcacheBenchRouterInfo>::init("ucache_bench_client", options);

  if (!routerPtr) {
    throw std::runtime_error("Failed to create mcrouter instance");
  }

  // Share ownership with the router instance
  routerInstance_ =
      std::shared_ptr<facebook::memcache::mcrouter::CarbonRouterInstance<
          UcacheBenchRouterInfo>>(
          routerPtr,
          [](facebook::memcache::mcrouter::CarbonRouterInstance<
              UcacheBenchRouterInfo>*) {
            // Custom deleter - don't delete, as the instance is managed by
            // static registry
          });

  if (FLAGS_verbose) {
    printf(
        "Connected to UcacheBench server via mcrouter at %s:%u (Thrift transport)\n",
        FLAGS_server_host.c_str(),
        FLAGS_server_port);
    printf("  McRouter proxy threads: %zu\n", options.num_proxies);
    printf("  Using per-thread clients for maximum QPS performance\n");
    if (FLAGS_additional_fanout > 0) {
      uint32_t totalConnections = FLAGS_additional_fanout + options.num_proxies;
      printf(
          "  Connection fanout enabled: %u additional connections (total: %u)\n",
          FLAGS_additional_fanout,
          totalConnections);
    } else {
      printf("  Connection fanout disabled (using default connections)\n");
    }
    if (FLAGS_enable_random_source_ip) {
      printf(
          "  Random source IP enabled: requests will use random source IPs for additional fanout\n");
    }
  }
}

UcacheBenchClient::~UcacheBenchClient() {
  // Clean up mcrouter instance
  if (routerInstance_) {
    routerInstance_->shutdown();
  }
}

UcacheBenchClient::WarmupResults UcacheBenchClient::warmup() {
  if (FLAGS_warmup_seconds == 0) {
    if (FLAGS_verbose) {
      printf("Warmup disabled (warmup_seconds=0)\n");
    }
    WarmupResults warmupResults;
    warmupResults.startTime = std::chrono::steady_clock::now();
    warmupResults.endTime = warmupResults.startTime;
    warmupResults.success = true;
    return warmupResults;
  }

  // Determine number of worker threads
  uint32_t numThreads = FLAGS_num_threads;
  if (numThreads == 0) {
    // Auto-detect: use half of available cores for worker threads
    numThreads = std::max(1u, std::thread::hardware_concurrency() / 2);
  }

  if (FLAGS_verbose) {
    printf(
        "Starting warmup for %u seconds with %u worker threads\n",
        FLAGS_warmup_seconds,
        numThreads);
  }

  auto startTime = std::chrono::steady_clock::now();
  auto endTime = startTime + std::chrono::seconds(FLAGS_warmup_seconds);

  // Thread-safe counters using atomics
  std::atomic<uint64_t> totalOps{0};
  std::atomic<uint64_t> setSuccesses{0};
  std::atomic<uint64_t> setErrors{0};
  std::atomic<bool> shouldStop{false};

  // Launch progress monitoring thread
  std::thread progressThread;
  if (FLAGS_verbose) {
    progressThread = std::thread([&]() {
      while (!shouldStop.load() && std::chrono::steady_clock::now() < endTime) {
        std::this_thread::sleep_for(std::chrono::seconds(5));

        if (shouldStop.load()) {
          break;
        }

        auto now = std::chrono::steady_clock::now();
        auto elapsed = std::chrono::duration<double>(now - startTime).count();

        uint64_t ops = totalOps.load();
        uint64_t successes = setSuccesses.load();
        uint64_t errors = setErrors.load();

        double avgQps = elapsed > 0 ? ops / elapsed : 0;
        double successRate = ops > 0 ? (successes * 100.0 / ops) : 0;

        printf(
            "Warmup progress: %lu ops (%.1f QPS avg), Success: %.1f%%, "
            "Errors: %lu\n",
            ops,
            avgQps,
            successRate,
            errors);
      }
    });
  }

  // Launch worker threads
  std::vector<std::thread> threads;
  threads.reserve(numThreads);

  for (uint32_t i = 0; i < numThreads; ++i) {
    threads.emplace_back([&, threadId = i]() {
      // Create per-thread client for maximum QPS performance
      auto threadClient =
          routerInstance_->createClient(0 /* max_outstanding_requests */);
      if (!threadClient) {
        if (FLAGS_verbose) {
          printf(
              "[Thread %u] Failed to create client, skipping warmup\n",
              threadId);
        }
        return;
      }

      uint64_t threadOps = 0;
      uint64_t threadSuccesses = 0;
      uint64_t threadErrors = 0;
      uint64_t lastSyncedOps = 0;
      uint64_t lastSyncedSuccesses = 0;
      uint64_t lastSyncedErrors = 0;

      while (std::chrono::steady_clock::now() < endTime) {
        // Generate random key-value pairs for warmup
        std::string key = generateKey();
        std::string value = generateValue();

        try {
          // Send the UcacheBench set operation and wait for result
          sendUcbSetRequestSync(threadClient, key, value, [&](UcbSetReply&& reply) {
            if (*reply.result_ref() == carbon::Result::STORED) {
              threadSuccesses++;
            } else {
              threadErrors++;
              if (FLAGS_verbose) {
                std::string msg;
                if (reply.message_ref().has_value() &&
                    !reply.message_ref()->empty()) {
                  msg = folly::to<std::string>(" - ", *reply.message_ref());
                }
                printf(
                    "[Thread %u] Warmup set failed for key: %s, result: %s%s\n",
                    threadId,
                    key.c_str(),
                    carbon::resultToString(*reply.result_ref()),
                    msg.c_str());
              }
            }
          });
        } catch (const std::exception& ex) {
          threadErrors++;
          if (FLAGS_verbose) {
            printf(
                "[Thread %u] Warmup set exception for key %s: %s\n",
                threadId,
                key.c_str(),
                ex.what());
          }
        }

        threadOps++;

        // Update global atomics every 100 operations for progress monitoring
        if (threadOps % 100 == 0) {
          totalOps += (threadOps - lastSyncedOps);
          setSuccesses += (threadSuccesses - lastSyncedSuccesses);
          setErrors += (threadErrors - lastSyncedErrors);
          lastSyncedOps = threadOps;
          lastSyncedSuccesses = threadSuccesses;
          lastSyncedErrors = threadErrors;
        }

        // Brief sleep to avoid overwhelming the server during warmup
        if (threadOps % 1000 == 0) {
          std::this_thread::sleep_for(std::chrono::milliseconds(1));
        }
      }

      // Final update of remaining counters
      if (threadOps > lastSyncedOps) {
        totalOps += (threadOps - lastSyncedOps);
        setSuccesses += (threadSuccesses - lastSyncedSuccesses);
        setErrors += (threadErrors - lastSyncedErrors);
      }

      if (FLAGS_verbose) {
        printf(
            "[Thread %u] Warmup complete: %lu ops, %lu successes, %lu errors\n",
            threadId,
            threadOps,
            threadSuccesses,
            threadErrors);
      }
    });
  }

  // Wait for all worker threads to complete
  for (auto& thread : threads) {
    thread.join();
  }

  // Stop progress thread
  shouldStop.store(true);
  if (progressThread.joinable()) {
    progressThread.join();
  }

  WarmupResults warmupResults;
  warmupResults.startTime = startTime;
  warmupResults.endTime = std::chrono::steady_clock::now();
  warmupResults.totalOps = totalOps.load();
  warmupResults.setSuccesses = setSuccesses.load();
  warmupResults.setErrors = setErrors.load();
  warmupResults.success = (setSuccesses > 0);

  auto duration = std::chrono::duration<double>(
                      warmupResults.endTime - warmupResults.startTime)
                      .count();
  double warmupQps = warmupResults.totalOps / duration;

  if (FLAGS_verbose) {
    printf(
        "Warmup completed: %lu operations in %.2f seconds (%.1f QPS)\n",
        warmupResults.totalOps,
        duration,
        warmupQps);
    printf(
        "  Successes: %lu, Errors: %lu, Success Rate: %.1f%%\n",
        warmupResults.setSuccesses,
        warmupResults.setErrors,
        warmupResults.totalOps > 0
            ? (warmupResults.setSuccesses * 100.0 / warmupResults.totalOps)
            : 0.0);
    if (!warmupResults.success) {
      printf("  WARNING: Warmup failed - no successful SET operations!\n");
    }
  }

  return warmupResults;
}

UcacheBenchClient::BenchmarkResults UcacheBenchClient::runBenchmark() {
  // Determine number of worker threads
  uint32_t numThreads = FLAGS_num_threads;
  if (numThreads == 0) {
    // Auto-detect: use half of available cores for worker threads
    numThreads = std::max(1u, std::thread::hardware_concurrency() / 2);
  }

  if (FLAGS_verbose) {
    printf(
        "Starting benchmark for %u seconds with %u worker threads\n",
        FLAGS_duration_seconds,
        numThreads);
  }

  auto startTime = std::chrono::steady_clock::now();
  auto endTime = startTime + std::chrono::seconds(FLAGS_duration_seconds);

  // Thread-safe counters using atomics
  std::atomic<uint64_t> totalOps{0};
  std::atomic<uint64_t> getOps{0};
  std::atomic<uint64_t> setOps{0};
  std::atomic<uint64_t> getHits{0};
  std::atomic<uint64_t> getMisses{0};
  std::atomic<uint64_t> getErrors{0};
  std::atomic<uint64_t> setSuccesses{0};
  std::atomic<uint64_t> setErrors{0};

  // Mutex for latency vector (std::vector is not thread-safe)
  std::mutex latenciesMutex;
  std::vector<double> allLatencies;
  allLatencies.reserve(100000 * numThreads);

  // Launch worker threads
  std::vector<std::thread> threads;
  threads.reserve(numThreads);

  for (uint32_t i = 0; i < numThreads; ++i) {
    threads.emplace_back([&, threadId = i]() {
      // Create per-thread client for maximum QPS performance
      auto threadClient =
          routerInstance_->createClient(0 /* max_outstanding_requests */);
      if (!threadClient) {
        if (FLAGS_verbose) {
          printf(
              "[Thread %u] Failed to create client, skipping benchmark\n",
              threadId);
        }
        return;
      }

      uint64_t threadTotalOps = 0;
      uint64_t threadGetOps = 0;
      uint64_t threadSetOps = 0;
      uint64_t threadGetHits = 0;
      uint64_t threadGetMisses = 0;
      uint64_t threadGetErrors = 0;
      uint64_t threadSetSuccesses = 0;
      uint64_t threadSetErrors = 0;

      std::vector<double> threadLatencies;
      threadLatencies.reserve(100000);

      while (std::chrono::steady_clock::now() < endTime) {
        auto opStartTime = std::chrono::steady_clock::now();

        // Determine GET ratio based on distribution or flag
        double getRatio =
            distribution_.enabled ? distribution_.getRatio : FLAGS_get_ratio;
        bool isGet = (folly::Random::randDouble01() < getRatio);

        if (isGet) {
          // GET operation
          std::string key = generateKey();

          try {
            sendUcbGetRequestSync(threadClient, key, [&](UcbGetReply&& reply) {
              auto opEndTime = std::chrono::steady_clock::now();
              auto latencyMs = std::chrono::duration<double, std::milli>(
                                   opEndTime - opStartTime)
                                   .count();
              threadLatencies.push_back(latencyMs);

              threadGetOps++;

              if (*reply.result_ref() == carbon::Result::FOUND) {
                threadGetHits++;
              } else if (*reply.result_ref() == carbon::Result::NOTFOUND) {
                threadGetMisses++;

                // SET on GET miss to simulate real cache warming behavior
                std::string value = generateValue();
                try {
                  sendUcbSetRequestSync(
                      threadClient, key, value, [&](UcbSetReply&& setReply) {
                        if (*setReply.result_ref() == carbon::Result::STORED) {
                          threadSetSuccesses++;
                        } else {
                          threadSetErrors++;
                        }
                      });
                  threadSetOps++;
                } catch (const std::exception&) {
                  threadSetErrors++;
                }
              } else {
                threadGetErrors++;
              }
            });
          } catch (const std::exception&) {
            threadGetErrors++;
            auto opEndTime = std::chrono::steady_clock::now();
            auto latencyMs = std::chrono::duration<double, std::milli>(
                                 opEndTime - opStartTime)
                                 .count();
            threadLatencies.push_back(latencyMs);
          }
        } else {
          // SET operation
          std::string key = generateKey();
          std::string value = generateValue();

          try {
            sendUcbSetRequestSync(
                threadClient, key, value, [&](UcbSetReply&& reply) {
                  auto opEndTime = std::chrono::steady_clock::now();
                  auto latencyMs = std::chrono::duration<double, std::milli>(
                                       opEndTime - opStartTime)
                                       .count();
                  threadLatencies.push_back(latencyMs);

                  threadSetOps++;

                  if (*reply.result_ref() == carbon::Result::STORED) {
                    threadSetSuccesses++;
                  } else {
                    threadSetErrors++;
                  }
                });
          } catch (const std::exception&) {
            threadSetErrors++;
            auto opEndTime = std::chrono::steady_clock::now();
            auto latencyMs = std::chrono::duration<double, std::milli>(
                                 opEndTime - opStartTime)
                                 .count();
            threadLatencies.push_back(latencyMs);
          }
        }

        threadTotalOps++;

        // Rate limiting (per-thread)
        if (FLAGS_qps_target > 0) {
          double threadQpsTarget =
              static_cast<double>(FLAGS_qps_target) / numThreads;
          auto expectedDuration =
              std::chrono::duration<double>(threadTotalOps / threadQpsTarget);
          auto actualDuration = std::chrono::steady_clock::now() - startTime;

          if (actualDuration < expectedDuration) {
            auto sleepDuration = expectedDuration - actualDuration;
            std::this_thread::sleep_for(sleepDuration);
          }
        }
      }

      // Update global counters atomically
      totalOps += threadTotalOps;
      getOps += threadGetOps;
      setOps += threadSetOps;
      getHits += threadGetHits;
      getMisses += threadGetMisses;
      getErrors += threadGetErrors;
      setSuccesses += threadSetSuccesses;
      setErrors += threadSetErrors;

      // Merge latencies with mutex
      {
        std::lock_guard<std::mutex> lock(latenciesMutex);
        allLatencies.insert(
            allLatencies.end(), threadLatencies.begin(), threadLatencies.end());
      }

      if (FLAGS_verbose) {
        printf(
            "[Thread %u] Benchmark complete: %lu ops, GET: %lu/%lu/%lu, SET: %lu/%lu\n",
            threadId,
            threadTotalOps,
            threadGetHits,
            threadGetMisses,
            threadGetErrors,
            threadSetSuccesses,
            threadSetErrors);
      }
    });
  }

  // Wait for all threads to complete
  for (auto& thread : threads) {
    thread.join();
  }

  BenchmarkResults results;
  results.startTime = startTime;
  results.endTime = std::chrono::steady_clock::now();
  results.totalOps = totalOps.load();
  results.getOps = getOps.load();
  results.setOps = setOps.load();
  results.getHits = getHits.load();
  results.getMisses = getMisses.load();
  results.getErrors = getErrors.load();
  results.setSuccesses = setSuccesses.load();
  results.setErrors = setErrors.load();
  results.latencies = std::move(allLatencies);

  return results;
}

std::string UcacheBenchClient::generateKey() {
  uint32_t keyId = folly::Random::rand32(FLAGS_key_count);

  if (distribution_.enabled) {
    // Use production distribution for key size
    double avgKeySize = (folly::Random::randDouble01() < distribution_.getRatio)
        ? distribution_.getKeySizeAvg
        : distribution_.setKeySizeAvg;

    // Generate key with approximately the right size
    std::string baseKey = folly::sformat("key_{:08d}", keyId);

    // Pad or trim to match average key size
    int32_t targetSize = static_cast<int32_t>(avgKeySize);
    int32_t currentSize = static_cast<int32_t>(baseKey.size());

    if (currentSize < targetSize) {
      // Pad with deterministic characters based on keyId
      // This ensures the same keyId always generates the same full key
      for (int32_t i = 0; i < (targetSize - currentSize); ++i) {
        // Use keyId to generate deterministic padding
        baseKey.push_back('a' + ((keyId + i) % 26));
      }
    } else if (currentSize > targetSize && targetSize > 8) {
      // Trim (but keep at least "key_0000" format)
      baseKey = baseKey.substr(0, targetSize);
    }

    return baseKey;
  }

  // Default behavior: fixed format key
  return folly::sformat("key_{:08d}", keyId);
}

std::string UcacheBenchClient::generateValue() {
  if (distribution_.enabled) {
    // Sample value size from production percentile distribution
    uint32_t valueSize = sampleFromPercentiles(
        distribution_.setValueSizeP50,
        distribution_.setValueSizeP75,
        distribution_.setValueSizeP95,
        distribution_.setValueSizeP99);

    // Ensure reasonable bounds (match server's max alloc size of 64KB)
    if (valueSize < 1) {
      valueSize = 1;
    }
    if (valueSize > 65536) {
      valueSize = 65536; // Cap at 64KB to match server's max allocation
    }

    std::string value;
    value.reserve(valueSize);

    // Generate random value content
    for (uint32_t i = 0; i < valueSize; ++i) {
      value.push_back('a' + (folly::Random::rand32(26)));
    }

    return value;
  }

  // Default behavior: random size between min and max
  uint32_t valueSize =
      folly::Random::rand32(FLAGS_value_size_min, FLAGS_value_size_max + 1);

  std::string value;
  value.reserve(valueSize);

  // Generate random value content
  for (uint32_t i = 0; i < valueSize; ++i) {
    value.push_back('a' + (folly::Random::rand32(26)));
  }

  return value;
}

// mcrouter operations using UcacheBench service
void UcacheBenchClient::sendUcbGetRequestSync(
    facebook::memcache::mcrouter::CarbonRouterClient<
        UcacheBenchRouterInfo>::Pointer& client,
    const std::string& key,
    const std::function<void(UcbGetReply&&)>& callback) {
  UcbGetRequest request;
  request.key_ref() =
      carbon::Keys<folly::IOBuf>(std::move(*folly::IOBuf::copyBuffer(key)));

  // Set random source IP if enabled for connection fanout
  if (FLAGS_enable_random_source_ip) {
    // Generate a random IPv6 address in the format ::ffff:192.0.2.X
    // Using IPv4-mapped IPv6 addresses for simplicity
    uint8_t randomOctet = folly::Random::rand32(1, 255);
    std::string ipStr = folly::sformat("::ffff:192.0.2.{}", randomOctet);
    try {
      folly::IPAddress sourceIp(ipStr);
      request.setSourceIpAddr(sourceIp);
    } catch (const std::exception& e) {
      // Log and continue without source IP on error
      if (FLAGS_verbose) {
        printf("Warning: Failed to set source IP: %s\n", e.what());
      }
    }
  }

  // Use mcrouter async client with synchronization
  folly::fibers::Baton baton;
  UcbGetReply result;
  std::exception_ptr exceptionPtr = nullptr;

  bool success =
      client->send(request, [&](const UcbGetRequest&, UcbGetReply&& reply) {
        result = std::move(reply);
        baton.post();
      });

  if (!success) {
    // Failed to send - populate error message (result defaults to UNKNOWN)
    result.message_ref() = "Failed to send GET request to mcrouter";
    callback(std::move(result));
    return;
  }

  // Wait for response
  baton.wait();
  callback(std::move(result));
}

void UcacheBenchClient::sendUcbSetRequestSync(
    facebook::memcache::mcrouter::CarbonRouterClient<
        UcacheBenchRouterInfo>::Pointer& client,
    const std::string& key,
    const std::string& value,
    const std::function<void(UcbSetReply&&)>& callback) {
  UcbSetRequest request;
  request.key_ref() =
      carbon::Keys<folly::IOBuf>(std::move(*folly::IOBuf::copyBuffer(key)));
  request.value_ref() = *folly::IOBuf::copyBuffer(value);
  request.exptime_ref() = 3600; // 1 hour default TTL

  // Set random source IP if enabled for connection fanout
  if (FLAGS_enable_random_source_ip) {
    // Generate a random IPv6 address in the format ::ffff:192.0.2.X
    // Using IPv4-mapped IPv6 addresses for simplicity
    uint8_t randomOctet = folly::Random::rand32(1, 255);
    std::string ipStr = folly::sformat("::ffff:192.0.2.{}", randomOctet);
    try {
      folly::IPAddress sourceIp(ipStr);
      request.setSourceIpAddr(sourceIp);
    } catch (const std::exception& e) {
      // Log and continue without source IP on error
      if (FLAGS_verbose) {
        printf("Warning: Failed to set source IP: %s\n", e.what());
      }
    }
  }

  // Use mcrouter async client with synchronization
  folly::fibers::Baton baton;
  UcbSetReply result;

  bool success =
      client->send(request, [&](const UcbSetRequest&, UcbSetReply&& reply) {
        result = std::move(reply);
        baton.post();
      });

  if (!success) {
    // Failed to send - populate error message (result defaults to UNKNOWN)
    result.message_ref() = "Failed to send SET request to mcrouter";
    callback(std::move(result));
    return;
  }

  // Wait for response
  baton.wait();
  callback(std::move(result));
}

void UcacheBenchClient::printResults(const BenchmarkResults& results) {
  auto duration =
      std::chrono::duration<double>(results.endTime - results.startTime)
          .count();
  double qps = results.totalOps / duration;

  // Calculate latency percentiles
  std::vector<double> sortedLatencies = results.latencies;
  std::sort(sortedLatencies.begin(), sortedLatencies.end());

  double p50 = 0.0, p95 = 0.0, p99 = 0.0, p999 = 0.0;
  if (!sortedLatencies.empty()) {
    p50 = sortedLatencies[sortedLatencies.size() * 0.50];
    p95 = sortedLatencies[sortedLatencies.size() * 0.95];
    p99 = sortedLatencies[sortedLatencies.size() * 0.99];
    p999 = sortedLatencies[sortedLatencies.size() * 0.999];
  }

  double hitRatio = 0.0;
  if (results.getOps > 0) {
    hitRatio = static_cast<double>(results.getHits) / results.getOps * 100.0;
  }

  // Print warmup results first
  printf("\n=== UcacheBench Results ===\n");

  // Warmup Summary
  printf("WARMUP PHASE:\n");
  if (results.warmupResults.totalOps == 0) {
    printf("  Status: Disabled (warmup_seconds=0)\n");
  } else {
    auto warmupDuration =
        std::chrono::duration<double>(
            results.warmupResults.endTime - results.warmupResults.startTime)
            .count();
    double warmupQps = results.warmupResults.totalOps / warmupDuration;
    double warmupSuccessRate = results.warmupResults.totalOps > 0
        ? (results.warmupResults.setSuccesses * 100.0 /
           results.warmupResults.totalOps)
        : 0.0;

    printf(
        "  Status: %s\n",
        results.warmupResults.success ? "✓ SUCCESS" : "✗ FAILED");
    printf("  Duration: %.2f seconds\n", warmupDuration);
    printf(
        "  Operations: %lu (%.1f QPS)\n",
        results.warmupResults.totalOps,
        warmupQps);
    printf("  SET Successes: %lu\n", results.warmupResults.setSuccesses);
    printf("  SET Errors: %lu\n", results.warmupResults.setErrors);
    printf("  Success Rate: %.1f%%\n", warmupSuccessRate);

    if (!results.warmupResults.success) {
      printf("  ⚠️  WARNING: Cache may not be properly seeded for testing!\n");
    }
  }
  printf("\n");

  // Benchmark Summary
  printf("BENCHMARK PHASE:\n");
  printf("  Duration: %.2f seconds\n", duration);
  printf("  Total Operations: %lu\n", results.totalOps);
  printf("  QPS: %.1f\n", qps);
  printf("\n");

  printf("GET Operations: %lu\n", results.getOps);
  printf("  Hits: %lu\n", results.getHits);
  printf("  Misses: %lu\n", results.getMisses);
  printf("  Errors: %lu\n", results.getErrors);
  printf("  Hit Ratio: %.2f%%\n", hitRatio);
  printf("\n");

  printf("SET Operations: %lu\n", results.setOps);
  printf("  Successes: %lu\n", results.setSuccesses);
  printf("  Errors: %lu\n", results.setErrors);
  printf("\n");

  printf("Latency Percentiles (ms):\n");
  printf("  P50: %.2f\n", p50);
  printf("  P95: %.2f\n", p95);
  printf("  P99: %.2f\n", p99);
  printf("  P99.9: %.2f\n", p999);
  printf("\n");

  // Overall summary
  if (results.warmupResults.totalOps > 0 && !results.warmupResults.success) {
    printf(
        "🔍 ANALYSIS: Poor warmup may explain low hit ratio (%.2f%%). Consider:\n",
        hitRatio);
    printf("   - Increasing warmup duration (--warmup_seconds)\n");
    printf("   - Checking server-side SET operation handling\n");
    printf("   - Verifying cache capacity and eviction policies\n");
  } else if (results.warmupResults.totalOps > 0 && hitRatio < 10.0) {
    printf(
        "🔍 ANALYSIS: Low hit ratio (%.2f%%) despite successful warmup. Consider:\n",
        hitRatio);
    printf("   - Key distribution vs cache capacity\n");
    printf("   - Cache eviction policies\n");
    printf("   - TTL settings\n");
  }
}

void UcacheBenchClient::loadTrafficDistribution(const std::string& configFile) {
  // Read JSON config file
  std::ifstream file(configFile);
  if (!file.is_open()) {
    throw std::runtime_error(
        folly::sformat("Failed to open distribution config: {}", configFile));
  }

  std::string content(
      (std::istreambuf_iterator<char>(file)), std::istreambuf_iterator<char>());

  // Parse JSON using folly::dynamic
  folly::dynamic config;
  try {
    config = folly::parseJson(content);
  } catch (const std::exception& e) {
    throw std::runtime_error(
        folly::sformat("Failed to parse JSON config: {}", e.what()));
  }

  // Load configuration values
  distribution_.getRatio = config["get_ratio"].asDouble();
  distribution_.getKeySizeAvg = config["get_key_size_avg"].asDouble();
  distribution_.getResponseSizeAvg = config["get_response_size_avg"].asDouble();
  distribution_.getResponseSizeP50 = config["get_response_size_p50"].asDouble();
  distribution_.getResponseSizeP75 = config["get_response_size_p75"].asDouble();
  distribution_.getResponseSizeP95 = config["get_response_size_p95"].asDouble();
  distribution_.getResponseSizeP99 = config["get_response_size_p99"].asDouble();

  distribution_.setKeySizeAvg = config["set_key_size_avg"].asDouble();
  distribution_.setValueSizeAvg = config["set_value_size_avg"].asDouble();
  distribution_.setValueSizeP50 = config["set_value_size_p50"].asDouble();
  distribution_.setValueSizeP75 = config["set_value_size_p75"].asDouble();
  distribution_.setValueSizeP95 = config["set_value_size_p95"].asDouble();
  distribution_.setValueSizeP99 = config["set_value_size_p99"].asDouble();
}

uint32_t UcacheBenchClient::sampleFromPercentiles(
    double p50,
    double p75,
    double p95,
    double p99) const {
  // Sample percentile distribution using piecewise linear approximation
  // This creates a rough distribution that matches the percentiles

  double rand = folly::Random::randDouble01();

  // Map random value to percentile ranges
  if (rand < 0.50) {
    // 0-50%: linear interpolation between 0 and p50
    return static_cast<uint32_t>(rand / 0.50 * p50);
  } else if (rand < 0.75) {
    // 50-75%: linear interpolation between p50 and p75
    double t = (rand - 0.50) / 0.25;
    return static_cast<uint32_t>(p50 + t * (p75 - p50));
  } else if (rand < 0.95) {
    // 75-95%: linear interpolation between p75 and p95
    double t = (rand - 0.75) / 0.20;
    return static_cast<uint32_t>(p75 + t * (p95 - p75));
  } else if (rand < 0.99) {
    // 95-99%: linear interpolation between p95 and p99
    double t = (rand - 0.95) / 0.04;
    return static_cast<uint32_t>(p95 + t * (p99 - p95));
  } else {
    // 99-100%: values above p99 (1.2x to 1.5x p99)
    double t = (rand - 0.99) / 0.01;
    return static_cast<uint32_t>(p99 * (1.0 + 0.5 * t));
  }
}

} // namespace ucachebench
} // namespace facebook
